album/urls.py
from django.urls import path
from album.views import *

app_name = 'album'

urlpatterns = [
    path('', show_albums, name='show_albums'),
    path('create-album/', create_album, name='create_album'),
    path('search-books/', search_books, name='search_books'),
    path('albums/<slug:slug>/', show_album, name='show_album'),
    path('edit-album/<slug:slug>/', edit_album, name='edit_album'),
    path('album/<slug:slug>/remove-book/', remove_book_from_album, name='remove_book_from_album'),
    path('delete-album/<slug:slug>/', delete_album, name='delete_album'),
    path('search-albums/', search_albums, name='search_album'),
    path('json/', get_album_json, name='get_album_json'),
    path('create-album-flutter/', create_album_flutter, name='create_album_flutter'),
    path('edit-album-flutter/<slug:slug>/', edit_album_flutter, name='edit_album_flutter'),
    path('delete-album-flutter/<slug:slug>/', delete_album_flutter, name='delete_album_flutter'),
]

riviu_buku/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('login_register.urls')),
    path('book-detail/', include('review.urls')),
    path('profile/', include('myprofile.urls')),
    path('album/', include('album.urls')),
    path('upload/', include('upload_buku.urls')),
    path('auth/', include('authentication.urls')),
    path('mybooks/', include('mybooks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

album/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db import models
from homepage.models import Book

# Create your models here.

class Album(models.Model):
    name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book)
    description = models.CharField(max_length=256)
    cover_image = models.URLField(null=True, blank=True)

    def save(self, *args, **kwargs):
        # Save the album first to generate an id
        super().save(*args, **kwargs)

        # Then check if there are any books in the album
        if self.books.exists():
            # If there are books, set the cover image to the cover image of the first book
            self.cover_image = self.books.first().coverImg
            # Save the album again to update the cover image
            super().save(*args, **kwargs)

album/forms.py
from django import forms
from .models import Album

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['name', 'description']  # add other fields if needed

album/views.py
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_GET
from django.utils.text import slugify
from django.db.utils import IntegrityError
from login_register.urls import *
from homepage.models import Book
from .forms import AlbumForm
from album.models import Album
from django.shortcuts import render, get_object_or_404, redirect
from .models import Album
from .forms import AlbumForm
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def show_albums(request):
    # Get all albums
    albums = Album.objects.all()

    # Render the template with the albums
    return render(request, 'albums.html', {'albums': albums})

def delete_album(request, slug):
    album = get_object_or_404(Album, slug=slug)
    album.delete()
    return redirect('album:show_albums')

def show_album(request, slug):
    # Get the album with the given slug
    album = get_object_or_404(Album, slug=slug)

    # Render the album details page
    return render(request, 'album.html', {'album': album})

def create_album(request):
    if request.method == 'POST':
        print(request.POST)
        name = request.POST.get('name')
        description = request.POST.get('description')
        book_ids = request.POST.getlist('books')  # This should be a list of book IDs

        if not name:
            # Handle the case where no name is provided
            # For example, you could return an error message
            return render(request, 'create_album.html', {'error': 'Name is required'})

        # Create a new album object
        album = Album(name=name, description=description, user=request.user)


        # Generate a unique slug
        slug = slugify(name)
        unique_slug = slug
        num = 1
        while Album.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        album.slug = unique_slug

        album.save()

        # Add the selected books to the album
        books = Book.objects.filter(id__in=book_ids)
        album.books.set(books)

        album.save()

        return redirect('album:show_album', slug=album.slug)

    else:
        return render(request, 'create_album.html')
@login_required()
def edit_album(request, slug):
    # Get the album that you want to edit
    album = get_object_or_404(Album, slug=slug)
    books = Book.objects.all()
    book_ids = list(album.books.values_list('id', flat=True))

    if request.method == 'POST':
        # Get the updated data from the form
        name = request.POST.get('name')
        description = request.POST.get('description')
        book_ids = request.POST.getlist('books')  # This should be a list of book IDs

        if not name:
            return render(request, 'edit_album.html', {'error': 'Name is required', 'album': album})
        elif not description:
            return render(request, 'edit_album.html', {'error': 'Description is required', 'album': album})

        # Update the album object
        album.name = name
        album.description = description

        # Update the selected books in the album
        books = Book.objects.filter(id__in=book_ids)
        album.books.set(books)

        album.save()

        return redirect('album:show_album', slug=album.slug)

    else:
        return render(request, 'edit_album.html', {'album': album, 'books': books, 'book_ids': book_ids})

def add_book_to_album(request):
    album_id = request.GET.get('album_id')
    book_id = request.GET.get('book_id')
    album = get_object_or_404(Album, id=album_id)
    book = get_object_or_404(Book, id=book_id)
    added = False
    if book not in album.books.all():
        album.books.add(book)
        added = True
    return JsonResponse({'added': added, 'title': book.title})

def remove_book_from_album(request, slug):
    if request.method == 'POST':
        # Get the album and book
        album = get_object_or_404(Album, slug=slug)
        book_id = request.POST.get('book_id')
        book = get_object_or_404(Book, id=book_id)

        # Remove the book from the album
        album.books.remove(book)

        # Return a JSON response
        return JsonResponse({'success': True})

    else:
        return JsonResponse({'success': False})

@require_GET
def search_books(request):
    query = request.GET.get('query', '')
    books = Book.objects.filter(title__icontains=query)
    books_list = list(books.values())
    return JsonResponse(books_list, safe=False)

@require_GET
def search_albums(request):
    query = request.GET.get('query', '')
    albums = Album.objects.filter(name__icontains=query)
    album_list = list(albums.values())
    return JsonResponse(album_list, safe=False)

def get_book_json(request):
    book_item = Book.objects.all
    return HttpResponse(serializers.serialize('json', book_item))

def get_album_json(request):
    album_item = Album.objects.all()
    return HttpResponse(serializers.serialize("json", album_item), content_type="application/json")

def view_lists(request):
    lists = Album.objects.all()
    return render(request, 'lists.html', {'lists': lists})

def view_list(request, slug):
    list = get_object_or_404(Album, slug=slug)
    return render(request, 'list.html', {'list': list})

from django.http import JsonResponse
from django.core.serializers import serialize

# ... (existing imports)

@csrf_exempt
def create_album_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        name = data.get('name')
        description = data.get('description')
        book_ids = data.get('books')  # This should be a list of book IDs
        auth_user = User.objects.get(username=data["user"])

        if not name:
            return JsonResponse({'error': 'Name is required'}, status=400)

        # Create a new album object
        album = Album(name=name, description=description, user=auth_user)

        # Generate a unique slug
        slug = slugify(name)
        unique_slug = slug
        num = 1
        while Album.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        album.slug = unique_slug

        album.save()

        # Add the selected books to the album
        books = Book.objects.filter(id__in=book_ids)
        album.books.set(books)

        album.save()

        # Return the JSON representation of the created album
        serialized_album = serialize('json', [album])
        return JsonResponse({'message': 'Album created successfully', 'album': serialized_album}, status=201)

    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)


@csrf_exempt
def edit_album_flutter(request, slug):
    if request.method == 'POST':
        data = json.loads(request.body)
        name = data.get('name')
        description = data.get('description')
        book_ids = data.get('books')  # This should be a list of book IDs
        pk = data.get('pk')

        if not name:
            return JsonResponse({'error': 'Name is required'}, status=400)
        elif not description:
            return JsonResponse({'error': 'Description is required'}, status=400)

        album = Album.objects.get(pk=pk)

        # Update the album object
        album.name = name
        album.description = description

        # Update the selected books in the album
        books = Book.objects.filter(id__in=book_ids)
        album.books.set(books)

        album.save()

        return JsonResponse({'message': 'Album updated successfully', 'slug': album.slug}, status=200)

    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

@csrf_exempt
def delete_album_flutter(request, slug):
    if request.method == 'DELETE':
        album = get_object_or_404(Album, slug=slug)
        album.delete()
        return JsonResponse({'message': 'Album deleted successfully'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

album/templates/album.html
{% extends 'base.html' %}


{% block content %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ album.name }}</title>
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">

<div class="container mx-auto px-4 py-5">
    <h1 class="text-3xl font-bold mb-5">{{ album.name }}</h1>
    <div class="bg-white rounded shadow-lg p-4 mb-4">
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Name:</label>
            <p class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ album.name }}</p>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Description:</label>
            <p class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ album.description }}</p>
        <a href="{% url 'album:edit_album' album.slug %}" class="mt-2 inline-block bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Edit</a>
        </div>
    </div>
    <div id="albumBooks">
        <h2 class="text-2xl font-bold mb-4">Books:</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4" id="grid">
            {% for book in album.books.all %}
                <div class="bg-white rounded-lg shadow-md">
                    <img src="{{ book.coverImg }}" alt="{{ book.title }}" class="h-128 w-full rounded-t-lg object-cover">
                    <div id="book-{{ book.id }}" class="book bg-white rounded shadow-lg p-4 mb-4 flex justify-between items-center" data-title="{{ book.title|escapejs }}">
                        <h3 class="text-xl title">{{ book.title }}</h3>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

album/templates/albums.html
{% extends 'base.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Lists</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <div class="container mx-auto px-4 py-5">
        <section class="mb-10 text-center">
    <h2 class="text-2xl font-bold mb-4">Albums: Your Personal Book Collections</h2>
    <p class="text-lg">Gather, organize, and share. Albums are an ideal way to group books.</p>
    {% if user.is_authenticated %}
    <a href="{% url 'album:create_album' %}" class="mt-4 inline-block bg-purple-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Create an Album</a>
    {% endif %}
</section>
        <input type="text" id="albumSearch" oninput="searchAlbums()" placeholder="Search albums..." class="w-full mb-4 p-2 border rounded">
        <div id="albums-grid" class= "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        </div>
    </div>
</body>

<script>


function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function searchAlbums() {
    // Get the search query
    var query = document.getElementById('albumSearch').value;

    // Send a request to the server
    fetch(`search-albums/?query=${query}`)
        .then(response => response.json())
        .then(data => {
            // Get the grid element
            var grid = document.getElementById('albums-grid');

            // Clear the grid
            grid.innerHTML = '';

            // Loop through all albums and create new elements for each one
            for (var i = 0; i < data.length; i++) {
                var album = data[i];

                console.log(album)
                // Create new album element
                var albumElement = document.createElement('div');
                albumElement.className = 'bg-white rounded-lg shadow-md';
                albumElement.innerHTML = `
                <img src="${album.cover_image}" alt="${album.name}" class="h-128 w-full rounded-t-lg object-cover">
                    <h2 class="text-xl title">${album.name}</h2>
                    <p>${album.description}</p>
                    <a href="albums/${album.slug}/" class="mt-2 inline-block bg-purple-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">View Album</a>

                `;

                // Add new album element to the grid
                grid.appendChild(albumElement);
            }
        })
        .catch(error => console.error('Error:', error));
}
window.onload = searchAlbums
</script>
{% endblock content %}

album/templates/edit_album.html
{% extends 'base.html' %}

{% block content %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editing album</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">

    <div class="container mx-auto px-4 py-5">
        <h1 class="text-3xl font-bold mb-5">Edit album</h1>
        <form action="{% url 'album:edit_album' album.slug %}" method="post">
            {% csrf_token %}
            <div class="mb-4">
                <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Name:</label>
                <input id="name" type="text" name="name" value="{{ album.name }}" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <div class="mb-4">
                <label for="description" class="block text-gray-700 text-sm font-bold mb-2">Description:</label>
                <textarea id="description" name="description" rows="5" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ album.description }}</textarea>
            </div>
            <button type="submit" class="mt-2 inline-block bg-purple-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Save</button>
            </form>
       <form action="{% url 'album:delete_album' album.slug %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete Album" class="mt-2 inline-block bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
</form>
            <h2 class="text-2xl font-bold mb-4">Current Books:</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4" id="albumBooks">
        </div>
            <h2 class="text-2xl font-bold mb-4">Add books to your album</h2>
        <input type="text" id="bookSearch" onkeyup="searchBooks()" placeholder="Search for books" class="w-full mb-4 p-2 border rounded">
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4" id="grid">
        </div>

        <!-- Add your scripts here -->
        <script>
        var selectedBooks = {{ book_ids|safe }};
        var books = {};
        var isAddSelectedBooksCalled = false;

        function searchBooks() {
            // Get the search query
            var query = document.getElementById('bookSearch').value;

            // Send a request to the server
            fetch('/album/search-books/?query=' + query)
                .then(response => response.json())
                .then(data => {
                    // Get the grid element
                    var grid = document.getElementById('grid');

                    // Clear the grid
                    grid.innerHTML = '';

                    // Loop through all books and create new elements for each one
                    for (var i = 0; i < data.length; i++) {
                        var book = data[i];

                        // Store book in global variable
                        books[book.id] = book;

                        // Create new book element
                        var bookElement = document.createElement('div');
                        bookElement.className = 'bg-white rounded-lg shadow-md';
                        bookElement.innerHTML = `
                            <img src="${book.coverImg}" alt="${book.title}" class="h-128 w-full rounded-t-lg object-cover">
                            <div id="book-${book.id}" class="book bg-white rounded shadow-lg p-4 mb-4 flex justify-between items-center" data-title="${book.title}">
                                <h3 class="text-xl title">${book.title}</h3>
                                <button onclick="addToAlbum(${book.id})" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded add-to-album-button">Add to album</button>
                            </div>
                            `;
                        // Check if the book is already selected
                        var isChecked = selectedBooks.includes(book.id) ? 'checked' : '';
                        if (isChecked === 'checked') {
                            continue;
                        } else {
                            // Add new book element to the grid
                            grid.appendChild(bookElement);
                        }
                    }
                    if (!isAddSelectedBooksCalled) {
                        addSelectedBooks();
                        isAddSelectedBooksCalled = true;
                    }
            })
                .catch(error => console.error('Error:', error));
        }
        searchBooks();

        function addSelectedBooks(){
            for(var i = 0; i < selectedBooks.length; i++){
                var bookId = selectedBooks[i]
                // Get the book from global variable
                var book = books[bookId];
                console.log(bookId)

                // Create a new div for the book
                var bookDiv = document.createElement('div');
                bookDiv.id = 'book-' + bookId;
                bookDiv.className = 'book bg-white rounded shadow-lg p-4 mb-4 flex flex-col items-center';
                bookDiv.dataset.title = book.title;

                // Create a new img for the book cover
                var img = document.createElement('img');
                img.src = book.coverImg;
                img.alt = book.title;
                img.className = 'h-128 w-full rounded-t-lg object-cover';
                bookDiv.appendChild(img);

                // Create a new h3 for the book title
                var title = document.createElement('h3');
                title.className = 'text-xl title mt-4';
                title.textContent = book.title;
                bookDiv.appendChild(title);

                // Create a new button for removing the book
                var removeButton = document.createElement('button');
                removeButton.textContent = 'Remove';
                removeButton.className = 'bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded mt-4';
                removeButton.onclick = (function(bookDivLocal, bookIdLocal) {
                    return function() {
                        console.log(bookDivLocal);
                        document.getElementById('albumBooks').removeChild(bookDivLocal);

                        var index = selectedBooks.indexOf(bookIdLocal);
                        if (index > -1) {
                            selectedBooks.splice(index, 1);
                        }

                        var input = document.querySelector('input[name="books"][value="' + bookIdLocal + '"]');
                        form.removeChild(input);
                    };
                })(bookDiv, bookId);
                bookDiv.appendChild(removeButton);

                // Add the new div to the album
                document.getElementById('albumBooks').appendChild(bookDiv);
                // Create a new hidden input element for this book
                var input = document.createElement('input');
                input.type = 'hidden';
                input.name = 'books';
                input.value = bookId;

                // Add the hidden input element to the form
                var form = document.querySelector('form');
                form.appendChild(input);
            }
        }


        function addToAlbum(bookId) {
            // Get the book from global variable
            var book = books[bookId];

            // Create a new div for the book
            var bookDiv = document.createElement('div');
            bookDiv.id = 'book-' + bookId;
            bookDiv.className = 'book bg-white rounded shadow-lg p-4 mb-4 flex flex-col items-center';
            bookDiv.dataset.title = book.title;

            // Create a new img for the book cover
            var img = document.createElement('img');
            img.src = book.coverImg;
            img.alt = book.title;
            img.className = 'h-128 w-full rounded-t-lg object-cover';
            bookDiv.appendChild(img);

            // Create a new h3 for the book title
            var title = document.createElement('h3');
            title.className = 'text-xl title mt-4';
            title.textContent = book.title;
            bookDiv.appendChild(title);

            // Create a new button for removing the book
            var removeButton = document.createElement('button');
            removeButton.textContent = 'Remove';
            removeButton.className = 'bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded mt-4';
            removeButton.onclick = function() {
                // Remove the book div from the album
                document.getElementById('albumBooks').removeChild(bookDiv);

                // Remove the book id from selectedBooks
                var index = selectedBooks.indexOf(bookId);
                if (index > -1) {
                    selectedBooks.splice(index, 1);
                }

                // Remove the hidden input element for this book
                var input = document.querySelector('input[name="books"][value="' + bookId + '"]');
                form.removeChild(input);
            };
            bookDiv.appendChild(removeButton);


            // Add the new div to the album
            document.getElementById('albumBooks').appendChild(bookDiv);

            selectedBooks.push(bookId);

            // Create a new hidden input element for this book
            var input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'books';
            input.value = bookId;

            // Add the hidden input element to the form
            var form = document.querySelector('form');
            form.appendChild(input);
            searchBooks();
        }

        function removeFromAlbum(bookId) {
            // Remove the book id from selectedBooks
            var index = selectedBooks.indexOf(bookId);
            if (index > -1) {
                selectedBooks.splice(index, 1);
            }

            // Remove the hidden input element for this book
            var input = document.querySelector('input[name="books"][value="' + bookId + '"]');
            form.removeChild(input);
        }
        </script>
    </div>
{% endblock content %}