album/urls.py
from django.urls import path
from album.views import *

app_name = 'album'

urlpatterns = [
    path('', show_albums, name='show_albums'),
    path('create-album/', create_album, name='create_album'),
    path('search-books/', search_books, name='search_books'),
    path('albums/<slug:slug>/', show_album, name='show_album'),
    path('edit-album/<slug:slug>/', edit_album, name='edit_album'),
    path('album/<slug:slug>/remove-book/', remove_book_from_album, name='remove_book_from_album'),
    path('delete-album/<slug:slug>/', delete_album, name='delete_album'),
    path('search-albums/', search_albums, name='search_album'),
    path('json/', get_album_json, name='get_album_json'),
    path('create-album-flutter/', create_album_flutter, name='create_album_flutter'),
    path('edit-album-flutter/<slug:slug>/', edit_album_flutter, name='edit_album_flutter'),
    path('delete-album-flutter/<slug:slug>/', delete_album_flutter, name='delete_album_flutter'),
]

myprofile/urls.py
from django.urls import path
from myprofile.views import *

app_name = 'myprofile'

urlpatterns = [
    path('', show_profile, name='show_profile'),
    path('complete/', complete_profile, name='complete_profile'),
    path('edit/', update_profile, name='update_profile'),
    path('update-bio/', update_bio, name='update_bio'),
    path('toggle-unlike-book/<int:book_id>/', toggle_unlike_book, name='toggle_unlike_book'),
    path('complete-profile-flutter/<int:id>/', complete_profile_flutter),
    path('get-profile-other-user/', get_profile_other_user),
    path('get-books-liked-by-user-flutter/', get_books_liked_by_user_flutter),
    path('get-profile-user/<int:id>', get_profile_user)
]

riviu_buku/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('login_register.urls')),
    path('book-detail/', include('review.urls')),
    path('profile/', include('myprofile.urls')),
    path('album/', include('album.urls')),
    path('upload/', include('upload_buku.urls')),
    path('auth/', include('authentication.urls')),
    path('mybooks/', include('mybooks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myprofile/models.py
from django.db import models
from django.contrib.auth.models import User

class ProfileUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, blank=True)
    avatar = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    handphone = models.CharField(max_length=15, blank=True) 
    bio = models.CharField(max_length=20, blank=True)  
    address = models.CharField(max_length=255, blank=True)

    def to_dict(self):
        return {
            'user_id': self.user.id,
            'username': self.user.username,
            'name': self.name,
            'avatar': self.avatar,
            'email': self.email,
            'handphone': self.handphone,
            'bio': self.bio,
            'address': self.address,
        }

myprofile/forms.py
from django.forms import ModelForm
from myprofile.models import ProfileUser
from django import forms

class ProfileForm(ModelForm):
    AVATAR_CHOICES = (
        ('avatar-default.jpeg', 'Default'),
        ('avatar1.jpeg', 'Avatar 1'),
        ('avatar2.jpeg', 'Avatar 2'),
        ('avatar3.jpeg', 'Avatar 3'),
        ('avatar4.jpeg', 'Avatar 4'),
        ('avatar5.jpeg', 'Avatar 5'),
        ('avatar6.jpeg', 'Avatar 6'),
        ('avatar7.jpeg', 'Avatar 7'),
    )
    avatar = forms.ChoiceField(choices=AVATAR_CHOICES, required=False)
    class Meta:
        model = ProfileUser
        fields = ["name", "avatar", "email", "handphone", "bio", "address"]

class UpdateProfileForm(ModelForm):
    class Meta:
        model = ProfileUser
        fields = ["name", "avatar", "email", "handphone", "bio", "address"]
    def __init__(self, *args, **kwargs):
        super(UpdateProfileForm, self).__init__(*args, **kwargs)

myprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from myprofile.models import ProfileUser
from homepage.models import Book
from django.http import HttpResponseRedirect, JsonResponse, Http404
from django.urls import reverse
from myprofile.forms import *
from django.views.decorators.http import require_POST
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.core import serializers

@login_required
def show_profile(request):
    user = request.user
    user_has_profile = ProfileUser.objects.filter(user=user).exists()

    liked_books = Book.objects.filter(liked_by_users=user)  # Fetch liked books

    context = {
        'username': request.user.username,
        'user_has_profile': user_has_profile,
    }

    if user_has_profile:
        profile_user = get_object_or_404(ProfileUser, user=user)
        context['profile_user'] = profile_user

    # Pass liked_books to the context
    context['liked_books'] = liked_books

    return render(request, 'myprofile.html', context)

@login_required
def complete_profile(request):
    form = ProfileForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        profile = form.save(commit=False)
        profile.user = request.user
        profile.save()
        messages.success(request, 'Your profile detail has been successfully added!')
        return HttpResponseRedirect(reverse('myprofile:show_profile'))
    
    context = {'form':form}
    return render(request, 'complete_profile.html', context)


@login_required
def update_profile(request):
    user = request.user
    try:
        profile = ProfileUser.objects.get(user=user)
    except ProfileUser.DoesNotExist:
        profile = None

    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile) 

        if form.is_valid():
            updated_profile = form.save(commit=False)
            updated_profile.user = user
            updated_profile.save()
            messages.success(request, 'Your profile details have been successfully updated!')
            return HttpResponseRedirect(reverse('myprofile:show_profile'))

    else:
        form = ProfileForm(instance=profile)

    context = {'form': form}
    return render(request, 'update_profile.html', context)

@login_required
def toggle_unlike_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if book.liked_by_users.filter(id=request.user.id).exists():
        book.liked_by_users.remove(request.user)
        liked = False
    else:
        liked = True

    return JsonResponse({'liked': liked})

@login_required
@require_POST
def update_bio(request):
    user = request.user
    new_bio = request.POST.get('bio', '')

    try:
        user.profileuser.bio = new_bio
        user.profileuser.save()

        # You can also return the updated bio in the response
        return JsonResponse({'success': True, 'new_bio': new_bio})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})

@csrf_exempt
def get_profile_user(request, id):
    if request.method == 'GET':

        auth_user = User.objects.get(pk=id)
        profile_user = ProfileUser.objects.get(user=auth_user)

        profile_dict = {
            "name": profile_user.name,
            "avatar": profile_user.avatar,
            "bio": profile_user.bio,
            "email": profile_user.email,
            "handphone": profile_user.handphone,
            "address": profile_user.address,
        }

        return JsonResponse(profile_dict, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def get_profile_other_user(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        auth_user = User.objects.get(username=data["user"])
        profile_user = ProfileUser.objects.get(user=auth_user)

        profile_dict = {
            "name": profile_user.name,
            "avatar": profile_user.avatar,
            "bio": profile_user.bio,
            "email": profile_user.email,
            "handphone": profile_user.handphone,
            "address": profile_user.address,
        }

        return JsonResponse(profile_dict, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def complete_profile_flutter(request, id):
    if request.method == 'POST':
        data = json.loads(request.body)

        auth_user = User.objects.get(pk=id)
        profile_user = ProfileUser.objects.get(user=auth_user)

        profile_user.name = data["name"]
        profile_user.avatar = data["avatar"]
        profile_user.bio = data["bio"]
        profile_user.email = data["email"]
        profile_user.handphone = data["handphone"]
        profile_user.address = data["address"]

        profile_user.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def get_books_liked_by_user_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        try:
            user = User.objects.get(username=data["user"])
            liked_books = Book.objects.filter(liked_by_users=user)
            serialized_books = serializers.serialize('json', liked_books)
            return JsonResponse({"status": "success", "liked_books": serialized_books}, status=200)
        except Http404:
            response_data = {'status': 'User not found', "liked_books": []}
            return JsonResponse(response_data, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"}, status=405)

myprofile/templates/complete_profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>
    Profile
</title>
{% endblock meta %}

{% block content %}
<head>
	<script>
		$(document).ready(function () {
			document.getElementById("navbar").remove();
			$("footer").remove();
		});
	</script>
</head>

<div class="w-screen h-screen flex justify-center items-center bg-ungu-muda">
    <div class="register w-[40rem] drop-shadow-2xl flex flex-col justify-center items-center bg-putih p-5 rounded-xl lg:scale-100 md:scale-90 scale-75">
        <h1 class="text-2xl font-bold mb-4">Lengkapi Profil</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="space-y-4"> 
                <div class="form-label mb-2">
                    <label for="id_name" class="font-bold">Nama:</label>
                    {{ form.name }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_avatar" class="font-bold">Avatar:</label>
                    {{ form.avatar }}
                </div>
                <div class="avatar-preview mt-2">
                    <img id="avatar-preview" src="" alt="Avatar Preview" class="w-24 h-24 rounded-full">
                </div>
                <div class="form-label mb-2">
                    <label for="id_email" class="font-bold">Email:</label>
                    {{ form.email }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_handphone" class="font-bold">Nomor Telepon:</label>
                    {{ form.handphone }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_bio" class="font-bold">Bio:</label>
                    {{ form.bio }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_address" class="font-bold">Alamat:</label>
                    {{ form.address }}
                </div>
                <div class="flex justify-center items-center">
                    <input class="btn mt-4 p-2 bg-ungu-muda rounded-lg h-10 w-full text-black hover:bg-ungu-tua" type="submit" name="submit" value="Selesai" />
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementById("id_avatar").addEventListener("change", function () {
        const selectedAvatar = this.value;
        
        const avatarPreview = document.getElementById("avatar-preview");

        avatarPreview.src = selectedAvatar ? "{% static 'images/' %}" + selectedAvatar : "";
    });
</script>
{% endblock content %}

myprofile/templates/myprofile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>
        Profile
    </title>
{% endblock meta %}

{% block content %}
    <div class="bg-cream-muda p-8 text-center">
        <h1 class="text-3xl font-bold mb-4">Profile</h1>
        <div class="mt-4">
            {% if user_has_profile %}
            <img src="{% static 'images/' %}{{ profile_user.avatar }}" alt="Avatar" class="h-48 w-48 rounded-full mx-auto my-4">
            <p class="text-2xl font-semibold">{{ profile_user.name }}</p>
            <p class="text-sm">@{{ username}}</p>
            <p class="text-lg italic text-purple-600" id="bio-text">{{ profile_user.bio }}</p>
            <button id="edit-bio-button" class="text-sm text-ungu-tua border-ungu-tua border rounded-full px-2 py-1 mt-2">Edit Bio</button>
            <form id="bio-form" class="mt-2">
                <textarea id="bio-input" class="w-full rounded border border-gray-300 p-2">{{ profile_user.bio }}</textarea>
                <button type="submit" class="bg-ungu-tua text-white px-4 py-2 rounded-full hover:bg-ungu-muda" style="text-decoration: none;">Save</button>
            </form>
            <p class="text-base mt-5">
                <img src="{% static 'images/icon-email.png' %}" alt="Email Icon" class="inline-block h-6 w-6 -mt-1 mr-2">
                {{ profile_user.email }}
            </p>
            <p class="text-base">
                <img src="{% static 'images/icon-handphone.png' %}" alt="Handphone Icon" class="inline-block h-6 w-6 -mt-1 mr-2">
                {{ profile_user.handphone }}
            </p>
            <p class="text-base md-5">
                <img src="{% static 'images/icon-address.png' %}" alt="Address Icon" class="inline-block h-6 w-6 -mt-1 mr-2">
                {{ profile_user.address }}
            </p>
            <a href="{% url 'myprofile:update_profile' %}"
                class="bg-ungu-tua text-white px-4 py-2 rounded-lg shadow-lg inline-block mt-5 hover:bg-ungu-muda" style="text-decoration: none;">Edit Profile</a>
            {% else %}
                <img src="{% static 'images/avatar-default.jpeg' %}" alt="Avatar" class="h-48 w-48 rounded-full mx-auto my-4">
                <p>@{{username}}</p>
                <p>Ayo lengkapi profilmu!</p>
                <a href="{% url 'myprofile:complete_profile' %}"
                    class="mt-5 bg-ungu-tua text-white px-4 py-2 rounded-lg shadow-lg inline-block" style="text-decoration: none;">Lengkapi Profil</a>
            {% endif %}
            <br>
        </div>
    </div>
    <div class="liked-books p-6 bg-putih">
        <div class="text-center ml-5 font-semibold text-lg">
            ❤️ Liked Books ❤️
        </div>
        <div class="mb-4 mt-5">
            <input type="text" id="bookSearch" placeholder="Search by Title" class="p-2 rounded border border-gray-300 w-full">
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6" id="bookList">
            {% for book in liked_books %}
            <div class="bg-cream-muda book-card rounded-lg shadow-xl p-4 mt-4 md-4 ml-3 mr-3 relative">
                <img src="{{ book.coverImg }}" alt="{{ book.title }}" class="w-full h-64 mb-4 object-cover rounded-t-lg">

                    <h2 class="text-xl font-semibold mb-2">{{ book.title }}</h2>
                    <p class="text-gray-500 mb-2">{{ book.author }}</p>
                    <button class="like-button text-white bg-ungu-tua px-4 py-2 rounded-full hover:bg-ungu-muda" data-book-id="{{ book.id }}">Unlike</button>
    
            </div>
            {% endfor %}
        </div>
    </div>       
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
         $("#edit-bio-button").click(function() {
        $("#bio-text").hide();
        $("#bio-form").show();
    });

    // Add an event listener to the bio form submission
    $("#bio-form").submit(function(event) {
        event.preventDefault(); // Prevent the default form submission

        const newBio = $("#bio-input").val();

        // Make an AJAX POST request to update the bio
        $.ajax({
            url: "{% url 'myprofile:update_bio' %}",
            method: "POST",
            data: { csrfmiddlewaretoken: "{{ csrf_token }}", bio: newBio },
            success: function(data) {
                // Update the UI with the new bio
                $("#bio-text").text(newBio).show();
                $("#bio-form").hide();
            },
            error: function(error) {
                console.error("Error updating bio:", error);
            }
        });
    });
        function filterBooks() {
            const searchQuery = $('#bookSearch').val().toLowerCase();
            $('#bookList .book-card').each(function() {
                const bookTitle = $(this).find('.text-xl').text().toLowerCase();
                if (bookTitle.includes(searchQuery)) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        }

        $('#bookSearch').on('input', filterBooks);

        async function getLikedBooks() {
        try {
            const response = await $.ajax({
                url: '/show_profile/',  
                method: 'GET',
                dataType: 'json',
            });
            return response.liked_books;
        } catch (error) {
            console.error('Error fetching liked books:', error);
            return [];
            }
        }
        async function refreshBooks() {
            const books = await getLikedBooks();
            const bookList = document.getElementById("bookList");

            bookList.innerHTML = '';

            books.forEach(book => {

            const bookCard = document.createElement('div');
            bookCard.className = "bg-cream-muda book-card rounded-lg shadow-xl p-4 mt-4 md-4 ml-3 mr-3 relative";
        
            const bookImage = document.createElement('img');
            bookImage.src = book.coverImg;
            bookImage.alt = book.title;
            bookImage.className = "w-full h-64 mb-4 object-cover rounded-t-lg";
        
            const bookDetails = document.createElement('div');
            bookDetails.className = "bg-white p-4 rounded-b-lg";
        
            const bookTitle = document.createElement('h2');
            bookTitle.className = "text-xl font-semibold mb-2";
            bookTitle.innerText = book.title;
        
            const bookAuthor = document.createElement('p');
            bookAuthor.className = "text-gray-500 mb-2";
            bookAuthor.innerText = book.author;
        
            const unlikeButton = document.createElement('button');
            unlikeButton.className = "like-button text-white bg-ungu-tua px-4 py-2 rounded-full";
            unlikeButton.innerText = "Unlike";
            unlikeButton.setAttribute('data-book-id', book.id);
        
            bookDetails.appendChild(bookTitle);
            bookDetails.appendChild(bookAuthor);
            bookDetails.appendChild(unlikeButton);
        
            bookCard.appendChild(bookImage);
            bookCard.appendChild(bookDetails);
        
            bookList.appendChild(bookCard);
            });
        } 

        async function toggleUnlike(bookId, element) {
            $.ajax({
                url: `/profile/toggle-unlike-book/${bookId}/`,
                method: 'POST',
                data: { csrfmiddlewaretoken: "{{ csrf_token }}" },
                success: function(data) {
                    if (data.unliked) {
                        element.closest('.book-card').remove(); 
                    }
                }
            }).then(refreshBooks);
        }

        $(".like-button").click(function() {
            const bookId = $(this).data('book-id');
            const element = $(this);
            toggleUnlike(bookId, element);
        }); 

        
    </script>

{% endblock content %}

myprofile/templates/update_profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>
    Profile
</title>
{% endblock meta %}

{% block content %}
<head>
	<script>
		$(document).ready(function () {
			document.getElementById("navbar").remove();
			$("footer").remove();
		});
	</script>
</head>

<div class="w-screen h-screen flex justify-center items-center bg-ungu-muda">
    <div class="register w-[40rem] drop-shadow-2xl flex flex-col justify-center items-center bg-putih p-5 rounded-xl lg:scale-100 md:scale-90 scale-75">
        <h1 class="text-2xl font-bold mb-4">Edit Profil</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="space-y-4"> 
                <div class="form-label mb-2">
                    <label for="id_name" class="font-bold">Nama:</label>
                    {{ form.name }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_avatar" class="font-bold">Avatar:</label>
                    {{ form.avatar }}
                </div>
                <div class="avatar-preview mt-2">
                    <img id="avatar-preview" src="" alt="Avatar Preview" class="w-24 h-24 rounded-full">
                </div>
                <div class="form-label mb-2">
                    <label for="id_email" class="font-bold">Email:</label>
                    {{ form.email }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_handphone" class="font-bold">Nomor Telepon:</label>
                    {{ form.handphone }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_bio" class="font-bold">Bio:</label>
                    {{ form.bio }}
                </div>
                <div class="form-label mb-2">
                    <label for="id_address" class="font-bold">Alamat:</label>
                    {{ form.address }}
                </div>
                <div class="flex justify-center items-center">
                    <input class="btn mt-4 p-2 bg-ungu-muda rounded-lg h-10 w-full text-black hover:bg-ungu-tua" type="submit" name="submit" value="Selesai" />
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementById("id_avatar").addEventListener("change", function () {
        const selectedAvatar = this.value;
        
        const avatarPreview = document.getElementById("avatar-preview");
        
        avatarPreview.src = selectedAvatar ? "{% static 'images/' %}" + selectedAvatar : "";
    });
</script>
{% endblock content %}