album/urls.py
from django.urls import path
from album.views import *

app_name = 'album'

urlpatterns = [
    path('', show_albums, name='show_albums'),
    path('create-album/', create_album, name='create_album'),
    path('search-books/', search_books, name='search_books'),
    path('albums/<slug:slug>/', show_album, name='show_album'),
    path('edit-album/<slug:slug>/', edit_album, name='edit_album'),
    path('album/<slug:slug>/remove-book/', remove_book_from_album, name='remove_book_from_album'),
    path('delete-album/<slug:slug>/', delete_album, name='delete_album'),
    path('search-albums/', search_albums, name='search_album'),
    path('json/', get_album_json, name='get_album_json'),
    path('create-album-flutter/', create_album_flutter, name='create_album_flutter'),
    path('edit-album-flutter/<slug:slug>/', edit_album_flutter, name='edit_album_flutter'),
    path('delete-album-flutter/<slug:slug>/', delete_album_flutter, name='delete_album_flutter'),
]

homepage/urls.py
from django.urls import path
from homepage.views import *

app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
    path('get_books', get_books, name='get_books'),
    path('get_books_by_id/<int:id>/', get_books_by_id, name='get_books_by_id'),
    path('create-fav-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('add_recommended_book_flutter/', add_recommended_book_flutter, name='add_recommended_book_flutter'),
    path('show_recommended_book_json/', show_recommended_book_json, name='show_recommended_book_json'), 
]

mybooks/urls.py
from django.urls import path
from mybooks.views import *

app_name = 'mybooks'
urlpatterns = [
    path('', show_main, name='show_main'),
    path('get_books', get_books, name='get_books'),
]

myprofile/urls.py
from django.urls import path
from myprofile.views import *

app_name = 'myprofile'

urlpatterns = [
    path('', show_profile, name='show_profile'),
    path('complete/', complete_profile, name='complete_profile'),
    path('edit/', update_profile, name='update_profile'),
    path('update-bio/', update_bio, name='update_bio'),
    path('toggle-unlike-book/<int:book_id>/', toggle_unlike_book, name='toggle_unlike_book'),
    path('complete-profile-flutter/<int:id>/', complete_profile_flutter),
    path('get-profile-other-user/', get_profile_other_user),
    path('get-books-liked-by-user-flutter/', get_books_liked_by_user_flutter),
    path('get-profile-user/<int:id>', get_profile_user)
]

riviu_buku/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('login_register.urls')),
    path('book-detail/', include('review.urls')),
    path('profile/', include('myprofile.urls')),
    path('album/', include('album.urls')),
    path('upload/', include('upload_buku.urls')),
    path('auth/', include('authentication.urls')),
    path('mybooks/', include('mybooks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

upload_buku/urls.py
from django.urls import path
from upload_buku.views import *

app_name = 'upload_buku'

urlpatterns = [
    path('', upload_buku, name='upload_buku'),
    path('create-flutter/', create_book_flutter, name='create_book_flutter')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      important: true,
      theme: {
        colors: {
          'ungu-muda':'#B8B8FF',
          'ungu-tua':'#9381FF',
          'cream-tua':'#FFD8BE',
          'cream-muda':'#FFEEDD',
          'putih':'#F8F7FF',
          'yellow': '#FACA15'
        }
      }
    }
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <!-- Link for CSS  -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  <!-- Link for JavaScript function -->
  <script src="#"></script>

  {% block meta %}
  {% endblock meta %}
</head>

<body class="flex flex-col h-screen justify-between">
  <div>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
<footer class="py-2 px-20 bg-ungu-tua text-white shadow-xl flex items-center
    justify-center">
    <div class="flex justify-center items-center font-bold">
        <span class="text-sm text-center">© 2023 <a href="{% url 'homepage:show_homepage' %}" class="hover:underline">Riviu Buku</a>. All Rights Reserved 🤍</span>
    </div>
</footer>

templates/navbar.html
<nav class="sticky z-50 top-0 md:px-20 px-4 py-4 bg-ungu-tua shadow-2xl md:flex
    md:items-center md:justify-between" id="navbar">
    <div class="flex gap-2 md:w-full justify-between">
        <a href="{% url 'homepage:show_homepage' %}">
            <div class="text-2xl font-bold text-[#fff] flex items-center cursor-pointer hover:text-cream-tua">
                Riviu Buku
            </div>
        </a>
        <div class="text-3xl cursor-pointer flex items-center md:hidden">
            <ion-icon name="menu" onclick="toggleMenu()" class="fill-white"></ion-icon>
        </div>
    </div>
    <div id="list-navbar"
        class="text-semibold font-medium text-white hidden md:show md:flex
        md:flex-row md:items-center md:justify-end">
        <div class="md:mx-5 my-3 md:my-0">
            <a href="{% url 'homepage:show_homepage' %}"
                class="hover:text-cream-muda hover:text-lg duration-500">Home</a>
        </div>
        <div class="md:mx-5 my-3 md:my-0">
            <a href="{% url 'album:show_albums' %}" class="hover:text-cream-muda
            hover:text-lg duration-500">Album</a>
        </div>
        {% if user.is_authenticated %}
        <div class="md:mx-5 my-3 md:my-0">
            <a href="{% url 'upload_buku:upload_buku' %}"
                class="hover:text-cream-muda hover:text-lg duration-500">Upload</a>
        </div>
        <div class="md:mx-5 my-3 md:my-0">
            <a href="{% url 'myprofile:show_profile' %}"
            class="hover:text-cream-muda hover:text-lg duration-500">Profile</a>
        </div>
        <div class="md:mx-5 my-3 md:my-0">
            <a href="{% url 'mybooks:show_main' %}"
            class="hover:text-cream-muda hover:text-lg duration-500">MyBooks</a>
        </div>
        <div class="md:mx-5 my-3 md:my-0">
            <button class="btn rounded-lg hover:cursor-pointer bg-cream-muda text-purple-800 hover:bg-cream-tua h-9 flex items-center justify-center"><a href="{% url 'login_register:logout_user' %}">Logout</a></button>
        </div>
        {% else %}
        <div class="md:mx-5 my-3 md:my-0">
            <button class="btn rounded-lg hover:cursor-pointer bg-cream-muda text-purple-800 hover:bg-cream-tua h-9 flex items-center justify-center"><a href="{% url 'login_register:login_user' %}">Login</a></button>
        </div>
        {% endif %}
    </div>
</nav>

<script>
    function toggleMenu() {
        var listNavbar = document.getElementById("list-navbar");
        listNavbar.classList.toggle("hidden");
    }
</script>