album/urls.py
from django.urls import path
from album.views import *

app_name = 'album'

urlpatterns = [
    path('', show_albums, name='show_albums'),
    path('create-album/', create_album, name='create_album'),
    path('search-books/', search_books, name='search_books'),
    path('albums/<slug:slug>/', show_album, name='show_album'),
    path('edit-album/<slug:slug>/', edit_album, name='edit_album'),
    path('album/<slug:slug>/remove-book/', remove_book_from_album, name='remove_book_from_album'),
    path('delete-album/<slug:slug>/', delete_album, name='delete_album'),
    path('search-albums/', search_albums, name='search_album'),
    path('json/', get_album_json, name='get_album_json'),
    path('create-album-flutter/', create_album_flutter, name='create_album_flutter'),
    path('edit-album-flutter/<slug:slug>/', edit_album_flutter, name='edit_album_flutter'),
    path('delete-album-flutter/<slug:slug>/', delete_album_flutter, name='delete_album_flutter'),
]

homepage/urls.py
from django.urls import path
from homepage.views import *

app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
    path('get_books', get_books, name='get_books'),
    path('get_books_by_id/<int:id>/', get_books_by_id, name='get_books_by_id'),
    path('create-fav-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('add_recommended_book_flutter/', add_recommended_book_flutter, name='add_recommended_book_flutter'),
    path('show_recommended_book_json/', show_recommended_book_json, name='show_recommended_book_json'), 
]

riviu_buku/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('login_register.urls')),
    path('book-detail/', include('review.urls')),
    path('profile/', include('myprofile.urls')),
    path('album/', include('album.urls')),
    path('upload/', include('upload_buku.urls')),
    path('auth/', include('authentication.urls')),
    path('mybooks/', include('mybooks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from review.models import Review
from cloudinary.models import CloudinaryField
# Create your models here.

class Book(models.Model):
    title = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)

    language = models.CharField(max_length=100, null=True, blank=True)
    genres = models.JSONField(null=True, blank=True)
    characters = models.JSONField(null=True, blank=True)
    edition = models.CharField(max_length=100, null=True, blank=True)
    pages = models.IntegerField(null=True, blank=True)

    publisher = models.CharField(max_length=100, null=True, blank=True)
    awards = models.JSONField(null=True, blank=True)
    numRatings = models.IntegerField(null=True, blank=True)
    numLikes = models.IntegerField(null=True, blank=True)
    coverImg = models.URLField(null=True, blank=True, default="https://res.cloudinary.com/dcf91ipuo/image/upload/v1702620170/defaultCoverImg_pvks08.jpg")
    review = models.ManyToManyField(Review)
    user = user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    liked_by_users = models.ManyToManyField(User, related_name="liked_books", blank=True)
    
    def __str__(self):
        return self.title
    
class RecommendedBook(models.Model):
    title = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.title
    
class FavoriteBook(models.Model):
    title = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.title

homepage/forms.py
from django.forms import ModelForm
from homepage.models import FavoriteBook

class BookForm(ModelForm):
    class Meta:
        model = FavoriteBook
        fields = [
            "title",
            "author",
            ]

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from homepage.models import Book, FavoriteBook, RecommendedBook
from django.views.decorators.csrf import csrf_exempt
import json

def show_homepage(request):
    books = Book.objects.all()
    context = {
        'books' : books,
    }

    return render(request, "homepage.html", context)

# Create your views here.
def get_books (request):
    data = Book.objects.all()
    return HttpResponse(serializers. serialize("json", data), content_type="application/json")

def get_books_by_id(request, id):
    book = Book.objects.filter(pk=id)  # Use filter to get a queryset with a single object
    if book.exists():  # Check if the book with the given ID exists
        return HttpResponse(serializers.serialize("json", book), content_type="application/json")
    else:
        return HttpResponse("Book not found", status=404)
    
@csrf_exempt
def add_book_ajax(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        author = request.POST.get("author")

        new_book = Book(title=title, author=author)
        new_book.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def show_xml(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Book.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@csrf_exempt
def add_recommended_book_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        new_book = RecommendedBook.objects.create(
            #user=data['user'],
            title=data['title'],
            author=data['author'],
        )
        new_book.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
def show_recommended_book_json(request):
    data = RecommendedBook.objects.all()
    #data=data[50:51]
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

homepage/templates/homepage.html
{% extends 'base.html' %}

{% block meta %}
  <title>
    Home
  </title>
{% endblock meta %}

{% block content %}
  <head>
    <style>
      .image-container {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
        grid-gap: 20px;
        max-width: 100%;
      }
    </style>
  </head>

  <body>
    <div class="bg-putih">
      <h1 class="pt-6 pb-6 text-center text-2xl font-bold font-serif">Selamat Datang di Riviu Buku!</h1>
      
      <div id="search-container" class="pl-10">
        <input type="text" id="search-input" placeholder="Search Books by Title">
        <button onclick="searchBooks()">Search</button>
      </div>

      <div id="book_cards" class="image-container pt-6 pb-6 pr-6 pl-6 w-95 rounded-2xl"></div>
      {% if user.is_authenticated %}
        <button type="button" class="btn btn-primary mb-3 ml-6 bg-ungu-muda" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
        {% endif %}

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Add Favorite Book</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form id="form" onsubmit="return false;">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="title" class="col-form-label">Title:</label>
                  <input type="text" class="form-control" id="title" name="title"></input>
                </div>
                <div class="mb-3">
                  <label for="author" class="col-form-label">Author:</label>
                  <input type="text" class="form-control" id="author" name="author"></input>
                </div>
              </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
            </div>
          </div>
        </div>
      </div>  

    </div>

  </body>

  <script>
    async function getBooks() {
      return fetch("{% url 'homepage:get_books' %}").then((res) => res.json())
    }

    async function refreshBooks() {
      document.getElementById("book_cards").innerHTML = "";
      const products = await getBooks();

      let htmlString = "";
      
      products.forEach((item) => {
        htmlString = `
          <div class="card bg-cream-muda rounded-lg cursor-pointer">
            <div class="card-body flex flex-col items-center">
              <a href="/book-detail/${item.pk}">
                <img class="card-img-top w-full cursor-pointer" id="clickable-image-${item.pk}" src="${item.fields.coverImg}" alt="${item.fields.title}">
                <h5 class="card-title font-bold text-lg mt-3 text-center">${item.fields.title}</h5>
              </a>
            </div>
          </div>`;
        document.getElementById("book_cards").innerHTML += htmlString;
      });

      products.forEach((item) => {
        const reviewUrl = `/book-detail/${item.pk}`; // call it here
        const idName = `clickable-image-${item.pk}`;
        const element = document.getElementById(idName);
        element.addEventListener('click', function() {
          window.location.href = reviewUrl;
        });

      });
    }
    refreshBooks();

    function searchBooks() {
      const searchInput = document.getElementById("search-input").value.toLowerCase();

      const cards = document.getElementsByClassName("card");
      for (const card of cards) {
        const title = card.querySelector(".card-title").textContent.toLowerCase();
        if (title.includes(searchInput)) {
          card.style.display = "block";
        } else {
          card.style.display = "none";
        }
      }
    }

    function addBook() {
      fetch("{% url 'homepage:add_book_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
      }).then(refreshProducts)

      document.getElementById("form").reset()
      return false
    }

    document.getElementById("button_add").onclick = addBook

  </script>
{% endblock content %}